# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\CompanyQuote\Client\Mapper\MapperInterface:
        class: App\CompanyQuote\Client\Mapper\Mapper


    App\CompanyQuote\Client\ClientInterface:
        class: App\CompanyQuote\Client\HttpClient
        arguments:
            $httpClient: '@yh_finance.client'

    App\CompanyQuote\CompanyQuoteServiceInterface:
        class: App\CompanyQuote\CompanyQuoteService

    App\Mailer\MailerServiceInterface:
        class: App\Mailer\MailerService
    
    App\Mailer\CsvReportGenerator: ~

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

when@test:
    services:
        Symfony\Component\HttpClient\MockHttpClient: ~ # Add response factory here

        App\CompanyQuote\Client\ClientInterface:
            class: App\CompanyQuote\Client\HttpClient
            arguments:
                $httpClient: '@Symfony\Component\HttpClient\MockHttpClient'
                $mapper: '@App\CompanyQuote\Client\Mapper\MapperInterface'
